5.UI/App.UI.WEB.ASP.MVC/Controllers/ScholershipController.cs
using App.Core.Helpers;
using App.Domain.Model;
using App.Framework.Business.ILogic;
using App.Framework.Business.Logic;
using App.UI.WEB.ASP.MVC.Base;
using App.UI.WEB.ASP.MVC.Helpers;
using App.UI.WEB.ASP.MVC.IBase;
using App.UI.WEB.ASP.MVC.Models;
using AutoMapper;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace App.UI.WEB.ASP.MVC.Controllers
{
    public class ScholershipController : BaseController
    {
        private readonly IAuthenticationUser authenticationUser;
        private readonly IScholarshipLogic scholarshipLogic;

        public ScholershipController(IAuthenticationUser authenticationUser, IScholarshipLogic scholarshipLogic)
        {
            this.authenticationUser = authenticationUser;
            this.scholarshipLogic = scholarshipLogic;
        }

        // GET: Scholership
        public async Task<ActionResult> Index()
        {
            ScholarshipListModel scholershipList = new ScholarshipListModel();
            scholershipList.Scholerships = new List<ScholarshipModel>();
            scholershipList.ScholershipFilters = new ScholershipFilters();
            scholershipList.ScholershipFilters.SearchText = "";

            try
            {
                byte AuthenticationRoleID = 0;
                byte.TryParse(this.authenticationUser.GetUserProfile(Base.AppConstant.UserPorfile.UserType).ToString(), out AuthenticationRoleID);

                ViewBag.AuthenticationRoleID = AuthenticationRoleID;

                List<Scholarship> scholarships = new List<Scholarship>();

                if (AuthenticationRoleID == (int)SecurityEnums.Role.Admin)
                {
                    scholarships = await this.scholarshipLogic.GetAllScholarships();
                }
                else if(AuthenticationRoleID == (int)SecurityEnums.Role.Graduate)
                {
                    long LoginUser_ID = 0;
                    long.TryParse(this.authenticationUser.GetUserProfile(Base.AppConstant.UserPorfile.ID).ToString(), out LoginUser_ID);

                    scholarships = await this.scholarshipLogic.GetScholarship(s => s.UserID == LoginUser_ID);
                }

                if (scholarships != null)
                {
                    scholershipList.Scholerships = Mapper.Map<List<Scholarship>, List<ScholarshipModel>>(scholarships);
                }

                return View(scholershipList);
            }
            catch (Exception ex)
            {
                List<string> ErrorMessage = CoreHelper.GetErrorMessage(ex);

                if (ErrorMessage.Any())
                {
                    Parallel.ForEach(ErrorMessage, ErrorMessageObj =>
                    {
                        ModelState.AddModelError("", ErrorMessageObj);
                    });

                    return View(scholershipList);
                }
                else
                {
                    throw;
                }
            }
        }


        [HttpGet]
        public async Task<ActionResult> Create(long? id)
        {
            ScholarshipModel scholarshipModel = new ScholarshipModel();

            try
            {
                if (id.HasValue)
                {
                    Scholarship scholarship = await this.scholarshipLogic.GetScholarshipByID(id.Value);

                    if (scholarship != null)
                        scholarshipModel = Mapper.Map<Scholarship, ScholarshipModel>(scholarship, scholarshipModel);
                }

                ViewBag.Create = true;
                ModelState.Clear();

                return PartialView(scholarshipModel);
            }
            catch (Exception ex)
            {
                throw;
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save(ScholarshipModel scholarshipModel)
        {
            try
            {
                ViewBag.SaveSuccess = false;
                TempData["Save"] = false;

                if (ModelState.IsValid)
                {
                    long LoginUser_ID = 0;
                    long.TryParse(this.authenticationUser.GetUserProfile(Base.AppConstant.UserPorfile.ID).ToString(), out LoginUser_ID);

                    //if (merchantModel.inputFile == null && TempData["inputFile"] != null)
                    //    merchantModel.inputFile = (HttpPostedFileBase)TempData.Peek("inputFile");

                    //if (merchantModel.inputFile != null)
                    //{
                    //    string SpecificPath = "Merchants/";
                    //    merchantModel.LogoPath = WebAppHelper.SaveFile(merchantModel.inputFile, AppConstant.FileType.Image, SpecificPath);
                    //    TempData["inputFile"] = merchantModel.inputFile;
                    //}

                    //if (!string.IsNullOrEmpty(merchantModel.LogoPath))
                    //    merchantModel.ImagePreview = WebAppHelper.GetAppSettingsValueByKey(AppConstant.AppSettingsKeys.FileSystemPath) + merchantModel.LogoPath;
                    //else
                    //    merchantModel.ImagePreview = "~/web-assets/images/noImage.png";

                    if (scholarshipModel.ID == 0)
                    {
                        Scholarship scholarship = Mapper.Map<ScholarshipModel, Scholarship>(scholarshipModel);

                        //product.Abbreviation = _MenuLanguage.Abbreviation[0].ToString().ToUpper() + _MenuLanguage.Abbreviation[1].ToString().ToLower();

                        scholarship.UserID = LoginUser_ID;
                        scholarship.Resume = "";

                        await this.scholarshipLogic.AddScholarship(scholarship);
                        await this.scholarshipLogic.SaveChanges();

                        scholarshipModel = new ScholarshipModel();

                    }
                    else
                    {
                        Scholarship scholarship = await this.scholarshipLogic.GetScholarshipByID(scholarshipModel.ID);
                        //string _LogoPath = merchant.LogoPath;

                        scholarship = Mapper.Map<ScholarshipModel, Scholarship>(scholarshipModel, scholarship);

                        await this.scholarshipLogic.UpdateScholarship(scholarship);
                        await this.scholarshipLogic.SaveChanges();

                        //if (_LogoPath != null && merchantModel.inputFile != null)
                        //    WebAppHelper.DeleteFile(_LogoPath);

                        //if (_LogoPath != null && string.IsNullOrEmpty(merchant.LogoPath))
                        //    WebAppHelper.DeleteFile(_LogoPath);

                        scholarshipModel = Mapper.Map<Scholarship, ScholarshipModel>(scholarship, scholarshipModel);
                    }

                    ModelState.Clear();

                    ViewBag.SaveSuccess = true;
                    TempData["Save"] = true;
                }

                return PartialView("Create", scholarshipModel);
            }
            catch (Exception ex)
            {
                List<string> ErrorMessage = CoreHelper.GetErrorMessage(ex);
                if (ErrorMessage.Any())
                {
                    Parallel.ForEach(ErrorMessage, ErrorMessageObj =>
                    {
                        ModelState.AddModelError("", ErrorMessageObj);
                    });

                    ViewBag.SaveSuccess = false;

                    return PartialView("Create", scholarshipModel);
                }
                else
                {
                    throw;
                }
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ListItemActions(ScholarshipModel scholarshipModel, string ActionName)
        {
            try
            {
                Scholarship scholarship = await this.scholarshipLogic.GetScholarshipByID(scholarshipModel.ID);

                if (scholarship != null)
                {
                    if (ActionName == "Delete")
                    {
                        await this.scholarshipLogic.DeleteScholarship(scholarship);
                        await this.scholarshipLogic.SaveChanges();
                        ViewBag.DeleteSuccess = true;
                        TempData["Delete"] = true;
                    }
                    else
                    {
                        if (ActionName == "Edit")
                        {
                            if (!ModelState.IsValid)
                                return PartialView("ItemList", scholarshipModel);

                            scholarship = Mapper.Map<ScholarshipModel, Scholarship>(scholarshipModel, scholarship);

                            ViewBag.SaveSuccess = true;
                        }

                        if(ActionName == "Approve")
                        {
                            scholarship.IsApproved = true;
                            ViewBag.SaveSuccess = true;
                        }
                        
                        if(ActionName == "Disapprove")
                        {
                            scholarship.IsApproved = false;
                            ViewBag.SaveSuccess = true;
                        }

                        byte AuthenticationRoleID = 0;
                        byte.TryParse(this.authenticationUser.GetUserProfile(Base.AppConstant.UserPorfile.UserType).ToString(), out AuthenticationRoleID);

                        ViewBag.AuthenticationRoleID = AuthenticationRoleID;

                        await this.scholarshipLogic.UpdateScholarship(scholarship);
                        await this.scholarshipLogic.SaveChanges();

                        ModelState.Clear();

5.UI/App.UI.WEB.ASP.MVC/Views/Scholership/Create.cshtml
@model App.UI.WEB.ASP.MVC.Models.ScholarshipModel

@{string HiddenValue = ViewBag.SaveSuccess != null ? ((bool)ViewBag.SaveSuccess).ToString() : "";}

@if (ViewBag.SaveSuccess != null && (bool)ViewBag.SaveSuccess == false)
{
    <div class="alert alert-danger" role="alert">
        Error
        @Html.ValidationSummary(false, "", new { @class = "ValidationSummary" })
    </div>
}

@using (Ajax.BeginForm("Save", "Scholership", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "SaveData" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(s => s.ID)
    @*@Html.HiddenFor(s => s.LogoPath)*@
    @Html.HiddenFor(s => s.Resume)
    @*@Html.HiddenFor(s => s.Resume, new { @id = "ImagePathHidden" })*@
    @Html.Hidden("SuccessHidden", @HiddenValue);

    <div class="form-row">

        <div class="col-md-12">
            <div class="form-row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(s => s.NationalID)
                        @Html.TextBoxFor(s => s.NationalID, new { @class = "form-control ", @maxLength = 500 })
                        @Html.ValidationMessageFor(s => s.NationalID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(s => s.University)
                        @Html.TextBoxFor(s => s.University, new { @class = "form-control ", @maxLength = 500 })
                        @Html.ValidationMessageFor(s => s.University, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(s => s.Major)
                        @Html.TextBoxFor(s => s.Major, new { @class = "form-control ", @maxLength = 100 })
                        @Html.ValidationMessageFor(s => s.Major, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(s => s.GPA)
                        @Html.TextBoxFor(s => s.GPA, new { @class = "form-control ", @maxLength = 5 })
                        @Html.ValidationMessageFor(s => s.GPA, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>


        <div class="col-md-12">
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-block btn-primary">Save</button>
            </div>
        </div>
    </div>
}

@*@if (ViewBag.SaveSuccess != null && (bool)ViewBag.SaveSuccess == true)
    {
        <script>
            $('#SearchBtn').click();
        </script>
    }*@

@if (ViewBag.Create != null && (bool)ViewBag.Create == true)
{
    <script>
        $('#createModal').modal('show');
    </script>
}

5.UI/App.UI.WEB.ASP.MVC/Views/Scholership/Index.cshtml
@model App.UI.WEB.ASP.MVC.Models.ScholarshipListModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="Index">

    @Html.Partial("List", Model)

</div>

5.UI/App.UI.WEB.ASP.MVC/Views/Scholership/ItemList.cshtml
@using App.Resources;
@model App.UI.WEB.ASP.MVC.Models.ScholarshipModel

@{
    string DivRenderName = "Div" + Model.ID.ToString();
    string deleteModal = "deleteModal" + Model.ID.ToString();
    string editModal = "editModal" + Model.ID.ToString();
    //string ActiveStatus = Model.SupportRTL ? "Deactivate Right to Left" : "Activate Right to Left";
    //string ActiveClass = Model.SupportRTL ? "active" : "";
}
@using (Ajax.BeginForm("ListItemActions", "Scholership", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = DivRenderName }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ID)
    @Html.HiddenFor(m => m.NationalID)
    @Html.HiddenFor(m => m.University)
    @Html.HiddenFor(m => m.Major)
    @Html.HiddenFor(m => m.GPA)
    @Html.HiddenFor(m => m.Resume)



    @*<div class="row">
        <div class="col">
            <button type="submit" name="ActionName" value="ImportToExcel" class="action-btn edit" data-toggle="modal">Download</button>
        </div>
    </div>*@

    <div class="superAdmin-users">
        <div class="title">
            <div class="container">

                <div class="row">
                    <div class="col">
                        <label>@AppResources.NationalID</label>
                        <p style="margin-bottom: 10px;font-weight: bold">@Model.NationalID</p>
                    </div>
                    <div class="col text-right">
                        <label>@AppResources.University</label>
                        <p style="margin-bottom: 10px;font-weight: bold">@Model.University</p>
                    </div>
                    <div class="col text-right">
                        <label>@AppResources.Major</label>
                        <p style="margin-bottom: 10px;font-weight: bold">@Model.Major</p>
                    </div>
                    <div class="col text-right">
                        <label>@AppResources.GPA</label>
                        <p style="margin-bottom: 10px;font-weight: bold">@Model.GPA</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="action container">
            <div class="row">
                <div class="col-md col">
                    @if (ViewBag.AuthenticationRoleID == 2)
                    {
                        <a class="action-btn edit" data-ajax="true" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-update="#SaveData" href="/Scholership/Create/@Model.ID"><i class="far fa-edit"></i> Edit</a>
                        if (Model.IsApproved)
                        {
                            <button type="button" name="ActionName" class="btn btn-success" disabled>Approved</button>
                        }
                    }
                    else if (ViewBag.AuthenticationRoleID == 1)
                    {
                        if (!Model.IsApproved)
                        {
                            <button type="submit" name="ActionName" value="Approve" class="action-btn edit" data-toggle="modal">Approve</button>
                        }
                        else
                        {
                            <button type="submit" name="ActionName" value="Disapprove" class="action-btn edit" data-toggle="modal">Disapprove</button>
                        }
                        @*<a class="action-btn edit" data-ajax="true" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-update="#SaveData" href="/Scholership/Create/@Model.ID"><i class="far fa-edit"></i> Approve</a>*@
                        @*<a class="action-btn edit" data-ajax="true" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-update="#SaveData" href="/Scholership/Create/@Model.ID"><i class="far fa-edit"></i> Save to excel</a>*@
                    }

                    @*<button type="button" class="action-btn delete" data-toggle="modal" data-target="#@deleteModal"><i class="far fa-times-circle"></i> Delete</button>*@
                    @*<button class="action-btn edit" data-ajax="true" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-update="#SaveData" href="/Admin/Merchant/Create/@Model.ID"><i class="far fa-edit"></i> Edit</button>
        <button class="action-btn delete" data-toggle="modal" data-target="#deleteModal"><i class="far fa-times-circle"></i> Delete</button>*@
                </div>
            </div>
        </div>
    </div>


    <!-- Delete Modal -->
    <div class="modal fade" id="@deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <div class="message text-center">
                        <h3>Are You Sure!</h3>
                        <p>You Want to Delete This recored?</p>
                        <div class="action">
                            <button type="submit" name="ActionName" value="Delete" class="delete" data-toggle="modal">Yes, delete</button>
                            <button class="cancel" data-dismiss="modal" aria-label="Close">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}

@if (ViewBag.DeleteSuccess != null && (bool)ViewBag.DeleteSuccess == true)
{
    <script>
        $('#SearchBtn').click();
    </script>
}


@if (ViewBag.SaveSuccess != null && (bool)ViewBag.SaveSuccess == false)
{
    <script>
        $('.modal-backdrop').remove();
        $('#@editModal').modal('show');
    </script>
}

<script>
    function setProductId(productId) {

        if ($('.SelectedProduct').length > 0) {
            $('.SelectedProduct').val(productId);
        }
    }
</script>

5.UI/App.UI.WEB.ASP.MVC/Views/Scholership/List.cshtml
@model App.UI.WEB.ASP.MVC.Models.ScholarshipListModel

<header>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="header-title">
                    <h3>Scholarship List</h3>
                </div>
            </div>
            <div class="col-md-6">
                <div class="header-action">
                    @if (ViewBag.AuthenticationRoleID == 2)
                    {
                        using (Ajax.BeginForm("Create", "Scholership", new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "SaveData" }))
                        {

                            <button class="create" data-toggle="modal">Create new Scholership</button>
                        }
                    }
                    else if (ViewBag.AuthenticationRoleID == 1)
                    {
                        <a class="create" href="@Url.Action("DownloadExcel","Scholership")">Export to Excel</a>
                    }
                </div>
            </div>
        </div>
    </div>
</header>

<section class="search">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @using (Ajax.BeginForm("Search", "Scholership", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "Index" }))
                {
                    <div class="form-group">
                        @Html.AntiForgeryToken()
                        @*@Html.TextBoxFor(m => m.ScholershipFilters.SearchText, new { @class = "form-control", @placeholder = "Enter Your Search" })*@
                        @Html.HiddenFor(m => m.ScholershipFilters.SearchText, new { @class = "form-control", @placeholder = "Enter Your Search" })
                        <button type="submit" name="ActionName" value="Search" id="SearchBtn" style="visibility:hidden"><i class="fas fa-search"></i></button>
                        <button type="submit" value="Refresh" name="ActionName" class="clear" onclick="location.reload();" style="visibility:hidden">Clear</button>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

<section class="super-admin">
    <div class="container">
        <div class="row ">
            @foreach (var scholarship in Model.Scholerships)
            {
                string DivName = "Div" + scholarship.ID.ToString();

                <div class="col-md-12" id="@DivName">
                    @Html.Partial("ItemList", scholarship)
                </div>
            }

            @if (@Model.Scholerships == null || !@Model.Scholerships.Any())
            {
                <div class="tab-pane" id="salads" role="tabpanel" aria-labelledby="salads-tab">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="empty text-center p-4">
                                    @if (ViewBag.Search != null && (bool)ViewBag.Search == true)
                                    {
                                        <h3>No Data Found Matched Your Search</h3>
                                    }
                                    else
                                    {
                                        <h3>No Scholarship Have Been Added Yet, Please Go to Create New Scholarship</h3>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</section>


<!-- Create Modal -->
<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title" id="staticBackdropLabel"> <i class="far fa-user"></i> Create New Merchant</p>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="SaveData">

                </div>
            </div>
        </div>
    </div>
</div>

<!-- Message Modal -->
<div class="modal fade" id="messageModal" tabindex="-1" aria-labelledby="messageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="message message-done text-center">
                    <img src="~/web-assets/images/checkmark.png">
                    @if (TempData["Delete"] != null && (bool)TempData["Delete"] == true)
                    {
                        <p>Data Deleted Successfully</p>
                    }
                    @if (TempData["Save"] != null && (bool)TempData["Save"] == true)
                    {
                        <p>Data Added Successfully</p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@if (TempData["Delete"] != null && (bool)TempData["Delete"] == true)
{
    <script>
        $('.modal-backdrop').remove();
        $('#messageModal').modal('show');
    </script>
}

@if (TempData["Save"] != null && (bool)TempData["Save"] == true)
{
    <script>
        $('.modal-backdrop').remove();
        $('#messageModal').modal('show');
    </script>
}